Added API Changes
happay/cms-utils-go pull request #5
Opened 2020-04-09 11:31 UTC by abhishek246006

2020-04-09 11:52 UTC, happay commented on util/env.go
> +	sess, err := session.NewSessionWithOptions(session.Options{
@abhishek246 Can you make the **sess** and **ssmsvc** objects as local variable on this file?

2020-04-09 11:54 UTC, happay reviewed
@abhishek246006  Could you make the **sess** and **ssmsvc** objects as local variable on the util/env.go file?

2020-04-09 18:56 UTC, happay reviewed
i think we should create an **aws** folder inside the connector and different go files for sqs, ses, s3, etc inside the **aws** folder.

2020-04-14 08:06 UTC, abhishek246006 commented
Please review and merge

2020-04-14 08:09 UTC, happay reviewed
Ideally, all the AWS functionalities should be inside their own package.
aws --> cred.go - This goes in aws package.
aws --> s3 --> s3.go - This goes in s3 package.
aws --> ses --> ses.go - This goes in ses package.
and so on.

2020-04-14 08:09 UTC, happay commented on connector/aws/ses.go
> +	NoReplyEmailId = "no-reply@happay.in"
What is the use of `NoReplyEmailId ` and `MatrixGroupEmail `?

2020-04-14 08:13 UTC, happay requested changes
@abhishek246006  I have put some comment. Please go through it and make the necessary changes.

2020-04-15 16:04 UTC, abhishek246006 commented
@happay I have made the changes requested

2020-04-16 07:04 UTC, merged